### ISSUE TITLE
renyi_value() does not contribute to the objective

### ISSUE THREAD

**Issue by negar-hassanpour** [optimization-for-data-driven-science/FairRenyi#1]
Thank you so much for the interesting paper and sharing your code.
In `FairLogisticRegression.py`, why the `renyi_value()` does not contribute to the objective function as well as the gradients? I think I'm missing something here.

**Comment by sinaBaharlouei** [comment]
The objective function is in the form of logistic_loss + Renyi_regularizer. To update theta we need to compute gradient of logistic_loss with respect to theta (which is exactly similar to the regular logistic regression) + the gradient of Renyi regularizer with respect to theta which is the output of grad2() function. And then we update w (the parameter of Renyi regularizer). We have used renyi_value() function just for evaluating the value of Renyi correlation after the optimization is done to make sure it converges to zero.

**Comment by negar-hassanpour** [comment]
Thanks for the explanation.
